language: node_js
node_js:
- node
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: tk/4wlId7e/RMXzTmttH2bWbTM4qbRHH9K38q3sy/pyp6CiM9NoG/R1e9oMT78oc7VZP/Eezau0R1e/Nl5jFSp7do+e1E+nxIlq7+ebNjyyX0zR7iqwWxYX6Wp90nyyIG+BE9L7HxPx+mnYhf7UtT/Sp7OEhcl+lvKbeE8AJ6aPciWvul8D5FAI3LMRFn5wBePcUsUWPgXv1SefkTBSn56LxMpmJXdx+kzizdTqPKVSs+eAqZmI2TJlN7UUBYzfpFwBrDvRPrQuQoKpZQk2ck9ehIvz8AEXrOrXluLca3g8crKt3aHX71ufSLBO1p+UmaxmkHY37BLVMdxDkGeecQA++og0uaqAhnuZsti2TGh2VMW1TXjZte0eg5uPLabEEooW6RZVcASbNq5a76lOHPid/QkWro2dKjEyP74sTqqFEUzCC5GjamqiHD5XW3f5pmpO2NK807HBA+RK0D51kn2TSFLr8G82CBJwco25gvnkc5VGoN1kjRgspyK89d8sE1ec1idE4XCQ5zElbeSG5DqDUXVIu78lZAQsO6iipyontIfMfW7UHp+t0EZc8HW0t9T5HpE8Q0IVWFa6zaYrhukoF6kXc5bNow1++m7FBDjy0q9WNnzHko+gOWIPrJ6mfWCLGFmfQ0z27b1biYFv2XniOGCPIKS+Qs9iSPasZdzM=
  app: garden-share-front-end
  on:
    repo: garden-share-08/garden-share-fe
    branch: main
  skip_cleanup: 'true'
