language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: VahYUAdbZmh3lNSbGNP/LDLPLNcVy3SJBd1ZcZJJs6ycwFQMAkuUqzzXnkH+ZPuycH6oYpcEVsAF4NF4x8Qsh5e57cF+1J01e3F452YuDKTM9rD0pq3w51s3RUo7KLLk2xMzM57ir+uWTVyX7Wx4JA4Is3aZDY/7j+//pOerUMOiEu6cTp/BLtf7V4C/OflR0DhrFcoOytDhXW4uBW4+j8i3D8069GfcuEEicUn0CT1suq9pnIjyq0n7kfgKPf+f9i7R+cY1VnzdgyHVDKRFvOT2jccO6Bbeb3ylGkwCWmAZo41duFbF/6EHAWrsCaGSkS6ExGsWMCAqdinFDnboSZeoVPT5TDgtoJqsnlS871QSarkRe9fp55xNsLo6NPjs+ccmNEzfFKi4nDQrbdSvBJjQKhMzx9PbJTujuae92DG0xkAa0c/FNaNKaeDe/VVaKhWuQQpIHJsn6Uml+Tads2mQFaqEJAQquH4rA7alyhTU9jcNDnu9abu4RFurOXBFQvsbXiA0RWZdqRaktr3hg/NqEyaPMpNhuCtG9w9tUGLAwXwRD8m/TdE7Fks117dfHUE2GaRlyROpZncg8P9WuWbPMrJwFZKu9leJ1kozjCjX1JWpiua2THzSKUwFwBD0G33I2v9V1GQZfQCopnfHGZDAVJbQSbfaxYfz/YRHo4M=
  app: garden-share-fe
  on:
    repo: garden-share-08/garden-share-fe
    branch: main
  skip_cleanup: 'true'
