language: node_js
node_js:
- node
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: QWtazTcHXI06Mp1TAMvPDa1Fw8ngpWmC+BUMDV1bsJTStngdyFR0PXJL7KuGUEFWd0VQKGya0BMCuW2nLCbAU/5+tNPEeNLkJ9y6ITHE6dVQ9tXbZWwNSnaN4yJBkFrCs2egYI7WWICKTsLrTaVXzXzCBXbR2L86T+F1yTJ6TjSJJ3P/onihTdwCIOH/E8kRSpf+BJPDn6JWmNRqNn4DPgGeR0DKfw8lxb1WrrL4hQpqUDKJaVRKGL2NTwt/36wpYNRZKTJ7Bd5aV60aVNT33a2+8d3jwOGCgo+pZHROKvmiah0AeCUVjPkliVf5sTAbIrZZ26l7pWrjFeBpt4h7fsQkD+Sp5IujhA8QWUt4OTxmT+9396saRsL4rmCq/vYR+v500Db9/K6y5L5APJ2SvduqVzFUyCPUV0zRCvrrVtMnKRwdZlL/a8jlts+6sbm6Ni448HoV8P90+vd5LuXXh5wkmybABMvwnXP1v105ssUWB139hxF/ivRIFYArDf1W/AJpXevTd53h9rjltja5Sq5G7TECtYw7RlIl3RKnicRc3TwaNcUL29CDJExDkPshSFG1QCy9tBHocfb33Mjc2tDtMwZdY7dcVIfaNSRWxHpUwLazINwNQ+P8hZIsHHT4dNEvxNCqatcijMWHZs3gkL8UOWeTtxxvmoTAoyBIRN8=
  app: garden-share-front-end
  on:
    repo: garden-share-08/garden-share-fe
    branch: main
  skip_cleanup: 'true'
