language: node_js
node_js:
- node
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: O9oY75RBIDcYupzmE417hJqiMMHZ4JG7hy36Ovh+5vO/3tdw6oehkzMHWqBAr3DxsYSHdKM85eZeWJ3W4ofliWdoj7Au1WJrWzq1Fdmad11gFDjv8lP2rJ0TI5vWs7H7ExSwSJFBPDypBzAQcmgKVRQnlbg7FAUhaKd+0Yzh/0ge0DQPJDyqfFgCk2HucfGfmYJLo8Rc0mDYJYu1ng0wdlOVDVX5MbCEEhg6JMcIoZ7ZOgNLGy7Gr6BTZBhzlPOkQiMfSI7lDtCsNaqjh4sNj8yGjvR3UWVpeeSBVRWU/+4fzbBNw4rYcra6CqBixyXJVO8UBE3TIQ6UzQ3NWbfuzEBl4nAL/pkm6nBlwA4sCvgYXOaUaA7FLCZaK4P+AfCSV3hA0q3voM99+6zMY7uzM67uowHSkUoO6PWHdx3DpleI/YvQw5dctFd6QBDO3AsoH6SoEagDakbnvFHHPaJuAwZvdBaGMNY5PEtJIwYD3yzy35QvCawi95y9sBhfGtetFP8TbDOCunUN0IoPycccEJsXZllsgSfMlaqTOdyIzNBz+17zIieruK7aGa/rFJ9dQMPpYWA1P9tme8qTROAsjeKOoWogmlIGBP1Rl1FHc6URqrlubWbs/kyUwRyqcynLUPycrYDUme5bH6oE3g4tzjd0PW7HkSXJwSF9FFiP93A=
  app: garden-share-front-end
  on:
    repo: garden-share-08/garden-share-fe
    branch: main
  skip_cleanup: 'true'
