language: node_js
node_js:
- node
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: TCqsVzJ+S/bqZo68pYdq1Phe6IIZJ7V1t9yeWyxGlTBY/e0thq0EIv3w3xaDYTNr9CACzTqXWPMZVEagifRzaHcaYE8V4dYFMxxwtcOQP0njP7+kRaheT0mFs7siV8djul4aTaLYpJ1XXVruag1v0qbo29u43nzEXrCiYQrq3qhHDEEz5Jf9cENjebpc9DF4xSe5JI1RM3xK/itDYat3OL66vLJ/FlBQszxobgq3a75AIxynD6eW1pqpMi7elo/g4a6c1ecsL/Q3fdBtU9JHO8y2a/Q8sxFXPgBXKkL/rzUaf2n4Inodc/2/KTof4ogImozJ0b/NeAfewuyEiRWs0QW7oHUeBWl3f6rJfCWunHAPcDBwhcAeyo6YfmOZGvHvJoxLQzk+oWzrrfUEW4Wkp99HjSg71z44Wc/QfHXfmNanQrg7zenny5zNl2ohcfYBFlK/hc/dHU/2tA6TM0vDkzN9csI1zPHRHO9iCdL0FyKC759d80zmlRo+IInH+tUOosCXSstg75+b8aJJQmwGIYlnEkvudpgMplccMLazB10R+sDG6vH3PjGd3Z8q2UgK6Kv3xE8sEhFdvXvd5tOT/jXIfNpni06CuITDwPeCkYIcb8UdbaVCvFMJkuzm9hx8IzTJzor41bYCOFu721WX5Xf0YfNxw7XiennuAM1q5hY=
  app: garden-share-front-end
  on:
    repo: garden-share-08/garden-share-fe
    branch: main
  skip_cleanup: 'true'
