language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: Fc9SwcYRiWcBHpTFz+xcAwzAlNcjvwKTAwKuYy4ytV6cARcrL5kU2XpHPpm9CUuJbH3Tl8RlaE1DF5QZgUBt4SEIb4IroItjVkCacUXac9CExMRpTWGCaeRhv1m8+8Rlk4xbCGvH2erAlGYp4N0wIzuuM28AlcyagUJ3hjnaCecbl96Cc9OSOb8Y7laYHaseGYI2sMN7NrnOSlso/xJ3rv2DnmU3UyAfdeTDKLvQd2Tg9r1nlUusWhkg5nUZ6QfDfMFAguYJMXncz4jDMByhpQHRSaQI9C+j2fWqCxRlLgtVlT565xqZl4N/NpnZ4RtHgYMy1kBwxqqbiuM2MoXWo5hRFegXQAeQZB/Jpww2ZgrLCmp7ipxiOUIqj/7mlWwOwvtRB7GapqyA1tYLjZrZhT78LhtFjADru35kDp4IfB62n2brHgkgIBEq6Ajpx0lTl7RbiVJjRFDi02E6MNXJ3wQTcXYdkhp0KbU60DFw22zsldwpkBvQ/o6c+8vspVf6s36X/ziVsUD5L9tTO0/Z8KJhfXuJSBypaHZXTFfb0e4QNv9q/Knpu2amC14qlwVX6ambbOJTE+jMxjQHq3/y61OV4mYSAPmHQ92Or8+JmFI0tinlWt067S0wXZJRnv+9mFh4QCgc2g4rkmIOc3S9TFfhOdRD16oaQNoB3qWsu5c=
  app: garden-share-fe
  on:
    repo: garden-share-08/garden-share-fe
    branch: main
  skip_cleanup: 'true'
